# install core tidyverse packages
install.packages("dplyr")
install.packages("ggplot2")
install.packages("readr")
install.packages("tidyr")
install.packages("shiny")
install.packages("shinythemes")
install.packages("DT")
install.packages("plotly")
install.packages("maps")